### ISSUE TITLE
Fehlerhafter Push durch .classpath-Datei

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/Fach_UEM1#20]
@Grrouti Sie haben vorhin Ihre Klasse gepusht, leider kam dort eine veränderte .classpath datei mit. Ich vermute, Sie verwenden eine andere IDE oder eine veraltete Version von Eclipse. Ich konnte Ihre Klasse also leider nicht rein mergen, bitte die Aufgabe nochmals abschließen, ich werde einige Konfigurationen ändern, dann sollte es klappen.

**Comment by Grrouti** [comment]
@L2P-Academy 
Ich habe jetzt wieder alles runtergeschmissen und neu gemacht , bitte Prüfen Sie meinen Push

**Comment by L2P-Academy** [comment]
@Grrouti Alles erledigt, läuft 💯
