### ISSUE TITLE
Bitte um eine Aufgabe

### ISSUE THREAD

**Issue by Grrouti** [L2P-Academy/Fach_UEM1#27]
@L2P-Academy ,
in den Bereichen  2,3 und 4 habe ich bereits Erfahrungen gesammelt.
1. Grafische Oberflächen / Layouts habe ich bis jetzt noch nicht mit gearbeitet.

Vielen Dank.

**Comment by L2P-Academy** [comment]
Alles klar :)

1. Für den Anfang: neues Package im Projekt erstellen mit dem Namen "GUI".
2. Legen Sie darin eine Klasse "Main Window" an, was später ihr Hauptfenster für die grafische Oberfläche darstellt und mit "extends" von JFrame erbt
3. Erzeugen Sie ein neues Objekt innerhalb der Klasse mit dem Namen "mainPanel" (JFrame)
4. Erzeugen Sie außerdem einen JButton und ein JTextfield, gern können Sie sich hier etwas überlegen, also welcher Nutzen, Name usw.
5. Beschäftigen Sie sich mit dem Thema "Borderlayout" und der Funktion dahinter. Sie können damit einzelne Elemente innerhalb des Panels anordnen.
6. Zur allgemeinen Vorgehensweise: Erst die neue Klasse erstellen inklusive "extends", dann die einzelnen Objekte anlegen. Sie können die Funktion in der Main testen. Hier ist aber einiges an Fleißarbeit nötig, da das Thema Java Swing sehr umfangreich ist. Zur Hilfestellung können Sie das Repository von der Zoo-App nehmen, dort ist einiges bereits geschehen :)

**Comment by L2P-Academy** [comment]
Wird erstmal geschlossen, da andere Aufgabe bearbeitet wird
