### ISSUE TITLE
Beispielaufgabe

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/Fach_UEM1#9]
- erstellen Sie eine neue Klasse mit dem Namen example.java
- legen Sie eine Methode an, mit Funktion xy
- achten Sie auf einheitliche Variablen-Bezeichner (englisch)

**Comment by CoPyMaus** [comment]
Bennenen Sie die CoPyMaus.java nach example.java um und ändern den Klassennamen.

Fertig
